version: '3.8'

services:
  web:
    build: .
    ports:
      - "5051:5051"
    environment:
      - DEBUG=1
      - DJANGO_SETTINGS_MODULE=llm_text_generator.settings
      - PYTHONUNBUFFERED=1
    volumes:
      - .:/app
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5051/"]
      interval: 30s
      timeout: 10s
      retries: 3 